---
title: "Traits that co-vary"
author: "SK"
date: "5/23/2019"
output: html_document
---





```{r setup, include = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = FALSE, 
                      warning = FALSE, message = FALSE)
```



```{r, results = "hide", include = FALSE}
require(rstan)
require(loo)
require(ggplot2)

source("R/main.R")
source("R/util.R")
source("R/bayesian.R")
source("R/statlearn.R")
source("R/modelcomparison.R")
source("R/ppc.R")

# models
m1 <- rstan::stan_model(file = "src/stan_files/M1.stan")
m1c <- rstan::stan_model(file = "src/stan_files/M1c.stan")
```








# Sim 1
## Simulate data:
  * N = 80 -> number of individuals
  * S = 200 -> number of SNPs
  * p.signal = 0.9 -> proportion of background SNPs
  * No strains

```{r}
# 1. simulate data
K <- 20
Nk <- 5
N <- K*Nk
S <- 100
p.signal = 0.9


set.seed(seed = 42133214)

# simulate slopes
beta <- replicate(n = K, ifelse(test = rep(x = runif(n = 1, min = 0, max = 1), times = Nk) > 0.5,
                                yes = rnorm(n = Nk, mean = runif(n = 1, min = 0, max = 2), sd = 1),
                                no = rnorm(n = Nk, mean = runif(n = 1, min = 3, max = 5), sd = 1)))

beta.mu <- colMeans(beta)
beta <- as.vector(beta)


alpha <- 0
Y <- alpha + beta

# no trait covariance
# cor <- rnorm(n = N, mean = 0.5, sd = 1)
# Y2 <- alpha + beta * cor

# no trait covariance
cor <- rnorm(n = N, mean = 0, sd = 1)
Y2 <- alpha + beta * cor


# simulate genotypes
X <- matrix(data = NA, nrow = N, ncol = S)
signal.snps <- c()
for(i in 1:S) {
  if(runif(n = 1, min = 0, max = 1) >= p.signal) {
    signal.snps <- c(signal.snps, i)
    X.vec <- sapply(X = (beta.mu-min(beta.mu))/(max(beta.mu)-min(beta.mu)), FUN = rbinom, n = Nk, size = 1)
    X.vec <- as.vector(X.vec)
    if(runif(n = 1, min = 0, max = 1) > 0.5) {
      X.vec[X.vec == 0] <- -1
      X[, i] <- X.vec
    }
    else {
      X.vec[X.vec == 1] <- -1
      X.vec[X.vec == 0] <- 1
      X[, i] <- X.vec
    }
  }
  else {
    X.vec <- replicate(n = K, sapply(X = rep(x = sample(x = c(0, 1), size = 1, replace = F), times = Nk), 
                                     FUN = rbinom, n = 1, size = 1))
    X.vec <- as.vector(X.vec)
    if(runif(n = 1, min = 0, max = 1) > 0.5) {
      X.vec[X.vec == 0] <- -1
      X[, i] <- X.vec
    }
    else {
      X.vec[X.vec == 1] <- -1
      X.vec[X.vec == 0] <- 1
      X[, i] <- X.vec
    }
    X[, i] <- X.vec
  }
}
rm(i)

# pack data for MLgwas
Yq <- matrix(data = cbind(Y, Y2), ncol = 2)
Yd <- matrix(data = 0, ncol = 0, nrow = N)
strains <- rep(x = 1:K, each = Nk)
data.list <- list(N = N,
                  Nk = K,
                  K = strains,
                  Ntq = 2,
                  Ntd = 0,
                  Ns = S,
                  Yq = Yq,
                  Yd = Yd,
                  X = X,
                  p.signal = p.signal,
                  signal.snps = signal.snps,
                  strains = strains)

gt.data <- getStanData(genotype = X,
                       traits = Yq,
                       trait.type = c("Q", "Q"),
                       strains = strains)


d1 <- list(data.list = data.list, 
           gt.data = gt.data)

rm(X, N, S, Y, Yq, Yd, data.list, gt.data, K, 
   strains, Nk, beta.mu, signal.snps, p.signal, 
   beta, alpha, i, X.vec)
```





## Analyze data
  * Comparison old vs new

```{r}
p <- rstan::sampling(object = m1,
                     data = d1$data.list,
                     iter = 1000,
                     warmup = 500,
                     chains = 4,
                     cores = 4,
                     control = list(adapt_delta = 0.9),
                     seed = 43397180)

pc <- rstan::sampling(object = m1c,
                     data = d1$data.list,
                     iter = 1000,
                     warmup = 500,
                     chains = 4,
                     cores = 4,
                     control = list(adapt_delta = 0.9),
                     seed = 43397180)
```



```{r, fig.width=5, fig.height=5}
p.summary <- summary(p, par = "beta")$summary[, "mean"]
pc.summary <- summary(pc, par = "beta")$summary[, "mean"]
plot(p.summary, pc.summary)
abline(0, 1, col = "red")
```


```{r, fig.width=5, fig.height=5}
summary(p, par = "rho")$summary[, "mean"]
summary(pc, par = "rho")$summary[, "mean"]
```


```{r}
summary(p, par = "L_rho")$summary[, "mean"]
summary(pfast, par = "L_rho")$summary[, "mean"]
```


```{r}
cor.test(d1$gt.data$Y[, 1], d1$gt.data$Y[, 2])
```

```{r}
cor.test(method = "spearman", d1$gt.data$Y[, 1], d1$gt.data$Y[, 2])
```

