---
title: "Performance M0"
author: "SK"
date: "5/23/2019"
output: html_document
---





```{r setup, include = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = FALSE, 
                      warning = FALSE, message = FALSE)
```



```{r, results = "hide", include = FALSE}
require(rstan)
require(loo)
require(ggplot2)

source("R/main.R")
source("R/util.R")
source("R/bayesian.R")
source("R/statlearn.R")
source("R/modelcomparison.R")
source("R/ppc.R")

# models
m0 <- rstan::stan_model(file = "src/stan_files/M0.stan")
m0fast <- rstan::stan_model(file = "src/stan_files/fastM0.stan")
```








# Sim 1
## Simulate data:
  * N = 80 -> number of individuals
  * S = 500 -> number of SNPs
  * p.signal = 0.9 -> proportion of background SNPs
  * No strains

```{r}
# 1. simulate data
N <- 80
S <- 500
p.signal = 0.9


set.seed(seed = 42133214)

# simulate slopes
beta <- replicate(n = N, ifelse(test = runif(n = 1, min = 0, max = 1) > 0.5,
                                yes = rnorm(n = 1, mean = 1, sd = 1),
                                no = rnorm(n = 1, mean = 4, sd = 1)))
alpha <- 0
Y <- alpha + beta

# simulate genotypes
X <- matrix(data = NA, nrow = N, ncol = S)
signal.snps <- c()
for(i in 1:S) {
  if(runif(n = 1, min = 0, max = 1) >= p.signal) {
    signal.snps <- c(signal.snps, i)
    X.vec <- sapply(X = (Y-min(Y))/(max(Y)-min(Y)), FUN = rbinom, n = 1, size = 1)
    if(runif(n = 1, min = 0, max = 1) > 0.5) {
      X.vec[X.vec == 0] <- -1
      X[, i] <- X.vec
    }
    else {
      X.vec[X.vec == 1] <- -1
      X.vec[X.vec == 0] <- 1
      X[, i] <- X.vec
    }
  }
  else {
    X[, i] <- sample(x = c(-1, 1), size = N, replace = T, prob = c(0.5, 0.5))
  }
}
rm(i)

# pack data for MLgwas
Yq <- matrix(data = Y, ncol = 1)
Yd <- matrix(data = 0, ncol = 0, nrow = N)
data.list <- list(N = N,
           Ntq = 1,
           Ntd = 0,
           Ns = S,
           Yq = Yq,
           Yd = Yd,
           X = X,
           p.signal = p.signal,
           signal.snps = signal.snps)

gt.data <- getStanData(genotype = X,
                       traits = Yq,
                       trait.type = "Q",
                       rep(x = 1, times = N))


d1 <- list(data.list = data.list, 
           gt.data = gt.data)

rm(X, N, S, Y, Yq, Yd, data.list, gt.data, 
   signal.snps, p.signal, beta, alpha, i, X.vec)
```





## Analyze data
  * Comparison old vs new

```{r}
p <- rstan::sampling(object = m0,
                     data = d1$data.list,
                     iter = 1000,
                     warmup = 500,
                     chains = 4,
                     cores = 4,
                     control = list(adapt_delta = 0.9),
                     seed = 43397180)



pfast <- rstan::sampling(object = m0fast,
                     data = d1$data.list,
                     iter = 1000,
                     warmup = 500,
                     chains = 4,
                     cores = 4,
                     control = list(adapt_delta = 0.9),
                     seed = 43397180)
```



```{r, fig.width=5, fig.height=5}
p.s <- summary(p, par = "beta")$summary[, "mean"]
pfast.s <- summary(pfast, par = "beta")$summary[, "mean"]
plot(p.s, pfast.s)
abline(0, 1, col = "red")
```

